# Generated by Django 5.1.7 on 2025-05-05 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promptbox_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promptboxitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promptbox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promptboxdialogue',
            name='promptbox_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue', to='promptbox_api.promptboxitem'),
        ),
    ]
