# Generated by Django 5.1.7 on 2025-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_user', models.BooleanField()),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('token_usage', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='chat_charts/')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='New Chat', max_length=100)),
                ('last_uploaded', models.DateTimeField(auto_now=True)),
                ('is_favourite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_uploaded'],
            },
        ),
    ]
